import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Java 基础',
      items: [
        {type: 'autogenerated', dirName: 'java-basic'},
      ],
    },
    {
      type: 'category',
      label: 'Spring 生态',
      items: [
        {type: 'autogenerated', dirName: 'spring'},
      ],
    },
    {
      type: 'category',
      label: '数据存储',
      items: [
        {type: 'autogenerated', dirName: 'data-storage'},
      ],
    },
    {
      type: 'category',
      label: '中间件与架构',
      items: [
        {type: 'autogenerated', dirName: 'middleware'},
      ],
    },
    {
      type: 'category',
      label: 'DevOps 与工具',
      items: [
        {type: 'autogenerated', dirName: 'devops'},
      ],
    },
    {
      type: 'category',
      label: 'AI 与大模型',
      items: [
        {type: 'autogenerated', dirName: 'ai'},
      ],
    },
  ],
};

export default sidebars;
